version: '3.4'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.8
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
  kafka:
    image: quay.io/debezium/kafka:1.8
    ports:
     - "9092:9092"
    links:
     - zookeeper
    environment:
     ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.228:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
     KAFKA_BROKER_ID: 1
     KAFKA_MIN_INSYNC_REPLICAS: 1
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - "1433:1433"
    environment:
     ACCEPT_EULA: Y
     MSSQL_PID: Standard
     SA_PASSWORD: Password!
     MSSQL_AGENT_ENABLED: true
  connect:
    image: quay.io/debezium/connect:1.8
    ports:
     - "8083:8083"
    links:
     - kafka
     - sqlserver
    environment:
     BOOTSTRAP_SERVERS: kafka:9092
     GROUP_ID: 1
     CONFIG_STORAGE_TOPIC: my_connect_configs
     OFFSET_STORAGE_TOPIC: my_connect_offsets
     STATUS_STORAGE_TOPIC: my_connect_statuses